abstract_concepts_sentiment = {
    "adventure": "positive",
    "affection": "positive",
    "ambition": "positive",
    "amusement": "positive",
    "anxiety": "negative",
    "awe": "positive",
    "balance": "positive",
    "beauty": "positive",
    "belonging": "positive",
    "bliss": "positive",
    "bravery": "positive",
    "camaraderie": "positive",
    "chaos": "negative",
    "charm": "positive",
    "cheerfulness": "positive",
    "compassion": "positive",
    "contentment": "positive",
    "courage": "positive",
    "curiosity": "positive",
    "delight": "positive",
    "determination": "positive",
    "dignity": "positive",
    "discipline": "positive",
    "despair": "negative",
    "destiny": "neutral",
    "divinity": "positive",
    "dreams": "positive",
    "ecstasy": "positive",
    "elegance": "positive",
    "empathy": "positive",
    "empowerment": "positive",
    "endurance": "positive",
    "enlightenment": "positive",
    "equality": "positive",
    "eternity": "neutral",
    "euphoria": "positive",
    "faith": "positive",
    "fear": "negative",
    "forgiveness": "positive",
    "freedom": "positive",
    "frustration": "negative",
    "frolic": "positive",
    "gaiety": "positive",
    "giddiness": "positive",
    "glee": "positive",
    "gleefulness": "positive",
    "grace": "positive",
    "gratitude": "positive",
    "harmony": "positive",
    "hope": "positive",
    "honor": "positive",
    "humor": "positive",
    "imagination": "positive",
    "ingenuity": "positive",
    "innocence": "positive",
    "integrity": "positive",
    "jollity": "positive",
    "joviality": "positive",
    "joy": "positive",
    "justice": "positive",
    "knowledge": "positive",
    "liberty": "positive",
    "lightheartedness": "positive",
    "liveliness": "positive",
    "love": "positive",
    "loyalty": "positive",
    "memory": "neutral",
    "merriment": "positive",
    "mirth": "positive",
    "mischief": "neutral",
    "morality": "positive",
    "mortality": "negative",
    "mundanity": "neutral",
    "mystery": "neutral",
    "nobility": "positive",
    "optimism": "positive",
    "passion": "positive",
    "patience": "positive",
    "pep": "positive",
    "perseverance": "positive",
    "playfulness": "positive",
    "pleasure": "positive",
    "pride": "positive",
    "prosperity": "positive",
    "quaintness": "positive",
    "radiance": "positive",
    "redemption": "positive",
    "respect": "positive",
    "reverence": "positive",
    "romance": "positive",
    "satisfaction": "positive",
    "sensuality": "positive",
    "serenity": "positive",
    "silliness": "neutral",
    "solitude": "neutral",
    "sparkle": "positive",
    "spirituality": "positive",
    "sympathy": "positive",
    "tenacity": "positive",
    "time": "neutral",
    "tranquility": "positive",
    "transcendence": "positive",
    "transience": "neutral",
    "truth": "positive",
    "unity": "positive",
    "valor": "positive",
    "vigor": "positive",
    "vivacity": "positive",
    "whimsy": "positive",
    "wisdom": "positive",
    "wonder": "positive",
    "wit": "positive",
    "yearning": "neutral",
    "zest": "positive",
    "anguish": "negative",
    "apathy": "negative",
    "bitterness": "negative",
    "desolation": "negative",
    "anguish": "negative",
    "apathy": "negative",
    "bitterness": "negative",
    "desolation": "negative",
    "discontent": "negative",
    "dishonesty": "negative",
    "doubt": "negative",
    "envy": "negative",
    "grief": "negative",
    "guilt": "negative",
    "hate": "negative",
    "injustice": "negative",
    "jealousy": "negative",
    "loneliness": "negative",
    "malice": "negative",
    "pain": "negative",
    "regret": "negative",
    "resentment": "negative",
    "sadness": "negative",
    "sorrow": "negative",
    "disappointment": "negative",
    "embarrassment": "negative",
    "fear": "negative",
    "humiliation": "negative",
    "ignorance": "negative",
    "misery": "negative",
    "prejudice": "negative",
    "shame": "negative",
    "torment": "negative",
    "worthlessness": "negative"
}

positive_sentiments = len([sentiment for sentiment in abstract_concepts_sentiment.values() if sentiment == "positive"])
negative_sentiments = len([sentiment for sentiment in abstract_concepts_sentiment.values() if sentiment == "negative"])
neutral_sentiments = len([sentiment for sentiment in abstract_concepts_sentiment.values() if sentiment == "neutral"])
total_sentiments = len(abstract_concepts_sentiment)

positive_percentage = (positive_sentiments / total_sentiments) * 100
negative_percentage = (negative_sentiments / total_sentiments) * 100
neutral_percentage = (neutral_sentiments / total_sentiments) * 100

print(f'Total number of abstract concepts: {total_sentiments}')
print(f'Total number of positive sentiments: {positive_sentiments}')
print(f'Total number of negative sentiments: {negative_sentiments}')
print(f'Total number of neutral sentiments: {neutral_sentiments}')
print(f'Positive Sentiment Percentage: {positive_percentage}%')
print(f'Negative Sentiment Percentage: {negative_percentage}%')
print(f'Neutral Sentiment Percentage: {neutral_percentage}%')
